-- Phase 1 foundation schema for:
-- - Auth-linked profiles and roles
-- - Branch structure
-- - Lightweight patient/family linkage
-- - RLS-friendly helper functions and policies

create extension if not exists pgcrypto with schema extensions;

do $$
begin
  if not exists (
    select 1
    from pg_type
    where typname = 'app_role'
      and typnamespace = 'public'::regnamespace
  ) then
    create type public.app_role as enum (
      'founder_admin',
      'branch_admin',
      'doctor',
      'counselor',
      'staff',
      'patient',
      'family_member',
      'pending_clinician',
      'pending_staff'
    );
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_type
    where typname = 'membership_status'
      and typnamespace = 'public'::regnamespace
  ) then
    create type public.membership_status as enum (
      'pending',
      'active',
      'suspended'
    );
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_type
    where typname = 'profile_language'
      and typnamespace = 'public'::regnamespace
  ) then
    create type public.profile_language as enum (
      'english',
      'urdu',
      'punjabi',
      'no_preference'
    );
  end if;
end;
$$;

create table if not exists public.branches (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  city text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username text unique,
  full_name text,
  phone_e164 text,
  preferred_language public.profile_language not null default 'english',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_username_format check (
    username is null or username ~ '^[a-z0-9_]{3,32}$'
  )
);

create table if not exists public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  role public.app_role not null,
  branch_id uuid references public.branches (id) on delete set null,
  status public.membership_status not null default 'active',
  assigned_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create unique index if not exists user_roles_user_role_branch_uniq
  on public.user_roles (
    user_id,
    role,
    coalesce(branch_id, '00000000-0000-0000-0000-000000000000'::uuid)
  );

create table if not exists public.patients (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique references auth.users (id) on delete set null,
  external_code text,
  primary_branch_id uuid references public.branches (id) on delete set null,
  created_by uuid references auth.users (id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.family_members (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique references auth.users (id) on delete set null,
  relation_label text,
  created_by uuid references auth.users (id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.patient_family_links (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.patients (id) on delete cascade,
  family_member_id uuid not null references public.family_members (id) on delete cascade,
  relationship_to_patient text,
  can_view_patient_profile boolean not null default true,
  can_view_tasks boolean not null default true,
  is_primary_contact boolean not null default false,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  unique (patient_id, family_member_id)
);

create index if not exists idx_user_roles_user_status
  on public.user_roles (user_id, status);

create index if not exists idx_user_roles_role_branch
  on public.user_roles (role, branch_id, status);

create index if not exists idx_patients_auth_user
  on public.patients (auth_user_id);

create index if not exists idx_family_members_auth_user
  on public.family_members (auth_user_id);

create index if not exists idx_patient_family_links_patient
  on public.patient_family_links (patient_id);

create index if not exists idx_patient_family_links_family
  on public.patient_family_links (family_member_id);

create or replace function public.set_row_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_branches_set_updated_at on public.branches;
create trigger trg_branches_set_updated_at
before update on public.branches
for each row
execute function public.set_row_updated_at();

drop trigger if exists trg_profiles_set_updated_at on public.profiles;
create trigger trg_profiles_set_updated_at
before update on public.profiles
for each row
execute function public.set_row_updated_at();

drop trigger if exists trg_patients_set_updated_at on public.patients;
create trigger trg_patients_set_updated_at
before update on public.patients
for each row
execute function public.set_row_updated_at();

drop trigger if exists trg_family_members_set_updated_at on public.family_members;
create trigger trg_family_members_set_updated_at
before update on public.family_members
for each row
execute function public.set_row_updated_at();

create or replace function public.has_any_active_role(target_roles public.app_role[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_roles ur
    where ur.user_id = auth.uid()
      and ur.status = 'active'
      and ur.role = any(target_roles)
  );
$$;

create or replace function public.has_active_role(
  target_role public.app_role,
  target_branch uuid default null
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_roles ur
    where ur.user_id = auth.uid()
      and ur.status = 'active'
      and ur.role = target_role
      and (
        target_branch is null
        or ur.branch_id is null
        or ur.branch_id = target_branch
      )
  );
$$;

create or replace function public.is_care_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.has_any_active_role(
    array[
      'founder_admin',
      'branch_admin',
      'doctor',
      'counselor',
      'staff'
    ]::public.app_role[]
  );
$$;

create or replace function public.handle_new_auth_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  cleaned_username text;
  resolved_language public.profile_language;
begin
  cleaned_username := nullif(
    lower(
      regexp_replace(
        coalesce(new.raw_user_meta_data ->> 'username', ''),
        '[^a-z0-9_]+',
        '',
        'g'
      )
    ),
    ''
  );

  resolved_language := case lower(coalesce(new.raw_user_meta_data ->> 'preferred_language', ''))
    when 'urdu' then 'urdu'
    when 'punjabi' then 'punjabi'
    when 'no_preference' then 'no_preference'
    else 'english'
  end;

  insert into public.profiles (
    id,
    username,
    full_name,
    phone_e164,
    preferred_language
  )
  values (
    new.id,
    cleaned_username,
    nullif(trim(coalesce(new.raw_user_meta_data ->> 'full_name', '')), ''),
    nullif(trim(coalesce(new.phone, '')), ''),
    resolved_language
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'on_auth_user_created_profile'
  ) then
    create trigger on_auth_user_created_profile
    after insert on auth.users
    for each row
    execute function public.handle_new_auth_user_profile();
  end if;
end;
$$;

alter table public.branches enable row level security;
alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;
alter table public.patients enable row level security;
alter table public.family_members enable row level security;
alter table public.patient_family_links enable row level security;

drop policy if exists branches_select_authenticated on public.branches;
create policy branches_select_authenticated
on public.branches
for select
to authenticated
using (true);

drop policy if exists branches_manage_admin on public.branches;
create policy branches_manage_admin
on public.branches
for all
to authenticated
using (
  public.has_any_active_role(
    array['founder_admin', 'branch_admin']::public.app_role[]
  )
)
with check (
  public.has_any_active_role(
    array['founder_admin', 'branch_admin']::public.app_role[]
  )
);

drop policy if exists profiles_self_or_staff_select on public.profiles;
create policy profiles_self_or_staff_select
on public.profiles
for select
to authenticated
using (
  id = auth.uid()
  or public.is_care_staff()
);

drop policy if exists profiles_self_or_staff_insert on public.profiles;
create policy profiles_self_or_staff_insert
on public.profiles
for insert
to authenticated
with check (
  id = auth.uid()
  or public.is_care_staff()
);

drop policy if exists profiles_self_or_staff_update on public.profiles;
create policy profiles_self_or_staff_update
on public.profiles
for update
to authenticated
using (
  id = auth.uid()
  or public.is_care_staff()
)
with check (
  id = auth.uid()
  or public.is_care_staff()
);

drop policy if exists user_roles_self_or_admin_select on public.user_roles;
create policy user_roles_self_or_admin_select
on public.user_roles
for select
to authenticated
using (
  user_id = auth.uid()
  or public.has_any_active_role(
    array['founder_admin', 'branch_admin']::public.app_role[]
  )
);

drop policy if exists user_roles_admin_manage on public.user_roles;
create policy user_roles_admin_manage
on public.user_roles
for all
to authenticated
using (
  public.has_any_active_role(
    array['founder_admin', 'branch_admin']::public.app_role[]
  )
)
with check (
  public.has_any_active_role(
    array['founder_admin', 'branch_admin']::public.app_role[]
  )
);

drop policy if exists patients_select_policy on public.patients;
create policy patients_select_policy
on public.patients
for select
to authenticated
using (
  public.is_care_staff()
  or auth_user_id = auth.uid()
  or exists (
    select 1
    from public.patient_family_links pfl
    join public.family_members fm
      on fm.id = pfl.family_member_id
    where pfl.patient_id = patients.id
      and fm.auth_user_id = auth.uid()
      and pfl.can_view_patient_profile
  )
);

drop policy if exists patients_staff_manage on public.patients;
create policy patients_staff_manage
on public.patients
for all
to authenticated
using (public.is_care_staff())
with check (public.is_care_staff());

drop policy if exists family_members_select_policy on public.family_members;
create policy family_members_select_policy
on public.family_members
for select
to authenticated
using (
  public.is_care_staff()
  or auth_user_id = auth.uid()
  or exists (
    select 1
    from public.patient_family_links pfl
    join public.patients p
      on p.id = pfl.patient_id
    where pfl.family_member_id = family_members.id
      and p.auth_user_id = auth.uid()
      and pfl.can_view_patient_profile
  )
);

drop policy if exists family_members_staff_manage on public.family_members;
create policy family_members_staff_manage
on public.family_members
for all
to authenticated
using (public.is_care_staff())
with check (public.is_care_staff());

drop policy if exists patient_family_links_select_policy on public.patient_family_links;
create policy patient_family_links_select_policy
on public.patient_family_links
for select
to authenticated
using (
  public.is_care_staff()
  or exists (
    select 1
    from public.patients p
    where p.id = patient_family_links.patient_id
      and p.auth_user_id = auth.uid()
  )
  or exists (
    select 1
    from public.family_members fm
    where fm.id = patient_family_links.family_member_id
      and fm.auth_user_id = auth.uid()
  )
);

drop policy if exists patient_family_links_staff_manage on public.patient_family_links;
create policy patient_family_links_staff_manage
on public.patient_family_links
for all
to authenticated
using (public.is_care_staff())
with check (public.is_care_staff());

grant usage on schema public to authenticated, anon;

grant select on public.branches to authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select on public.user_roles to authenticated;
grant select, insert, update, delete on public.patients to authenticated;
grant select, insert, update, delete on public.family_members to authenticated;
grant select, insert, update, delete on public.patient_family_links to authenticated;

grant usage, select on sequence public.user_roles_id_seq to authenticated;
